language: node_js

script:
  - npm run build
  - npm run test

matrix:
  include:
    - os: linux
      dist: xenial
      node_js: "12.4.0"
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update
        - sudo apt install -y protobuf-compiler
    - os: osx
      osx_image: xcode10.1
      node_js: "12.4.0"
